"""Type stubs for the compiled ``robustat_py._robustat_py`` extension module."""

from types import ModuleType
from typing import NoReturn, Sequence

import numpy as np
from numpy.typing import NDArray

__version__: str

Vector = NDArray[np.float64]
Matrix = NDArray[np.float64]
ArrayLike1D = Sequence[float] | Vector

class RobustError(ValueError): ...

# --- Losses and scales ---------------------------------------------------------

class Loss:
    def rho(self, r: float) -> float: ...
    def psi(self, r: float) -> float: ...
    def weight(self, r: float) -> float: ...
    def psi_prime(self, r: float) -> float: ...
    @property
    def tuning(self) -> float: ...
    @property
    def is_redescending(self) -> bool: ...
    @property
    def rho_sup(self) -> float | None: ...
    @property
    def name(self) -> str: ...
    def gaussian_efficiency(self) -> float: ...
    def asymptotic_variance(self) -> float: ...
    def influence(self, x: float) -> float: ...

class ScaleEstimator:
    def scale(self, data: ArrayLike1D) -> float: ...

def least_squares() -> Loss: ...
def l1() -> Loss: ...
def huber(k: float = ...) -> Loss: ...
def tukey(c: float = ...) -> Loss: ...
def cauchy(c: float = ...) -> Loss: ...
def welsch(c: float = ...) -> Loss: ...
def andrews(c: float = ...) -> Loss: ...
def hampel(a: float = ..., b: float = ..., c: float = ...) -> Loss: ...

def gaussian_efficiency(loss: Loss) -> float: ...
def asymptotic_variance(loss: Loss) -> float: ...
def breakdown_point(loss: Loss) -> float: ...

def mad(consistency: float = ...) -> ScaleEstimator: ...
def qn(consistency: float = ..., finite_sample_correction: bool = ...) -> ScaleEstimator: ...
def sn(consistency: float = ..., finite_sample_correction: bool = ...) -> ScaleEstimator: ...
def huber_proposal2(k: float = ...) -> ScaleEstimator: ...

LossArg = Loss | str | None
ScaleArg = ScaleEstimator | str | None

# --- Location ------------------------------------------------------------------

class LocationFit:
    @property
    def estimate(self) -> float: ...
    @property
    def scale(self) -> float: ...
    @property
    def iters(self) -> int: ...

class HodgesLehmannFit:
    @property
    def estimate(self) -> float: ...
    def gaussian_efficiency(self) -> float: ...
    def breakdown_point(self) -> float: ...

def m_location(
    data: ArrayLike1D,
    loss: LossArg = ...,
    scale: ScaleArg = ...,
    *,
    tol: float = ...,
    max_iter: int = ...,
) -> LocationFit: ...
def trimmed_mean(data: ArrayLike1D, alpha: float) -> float: ...
def winsorized_mean(data: ArrayLike1D, alpha: float) -> float: ...
def hodges_lehmann(data: ArrayLike1D) -> HodgesLehmannFit: ...

# --- Regression ----------------------------------------------------------------

class RegressionFit:
    # Note: wraps a non-Send loss, so this object is tied to its creating thread
    # (cannot be shared across threads / sent to another process).
    @property
    def coefficients(self) -> Vector: ...
    @property
    def scale(self) -> float: ...
    @property
    def residuals(self) -> Vector: ...
    @property
    def weights(self) -> Vector: ...
    @property
    def breakdown_point(self) -> float: ...
    def gaussian_efficiency(self) -> float: ...
    def asymptotic_variance(self) -> float: ...
    def influence(self, x: float) -> float: ...
    def coef_covariance(self, x: Matrix) -> Matrix: ...

class LtsFit:
    @property
    def coefficients(self) -> Vector: ...
    @property
    def scale(self) -> float: ...
    @property
    def residuals(self) -> Vector: ...
    @property
    def subset(self) -> list[int]: ...
    @property
    def objective(self) -> float: ...
    @property
    def coverage(self) -> int: ...
    @property
    def breakdown_point(self) -> float: ...
    def gaussian_efficiency(self) -> NoReturn: ...  # always raises NotImplementedError

class TheilSenFit:
    @property
    def slope(self) -> float: ...
    @property
    def intercept(self) -> float: ...
    def predict(self, x: float) -> float: ...
    def breakdown_point(self) -> float: ...
    def gaussian_efficiency(self) -> NoReturn: ...  # always raises NotImplementedError

class MEstimator:
    def __init__(
        self,
        loss: LossArg = ...,
        scale: ScaleArg = ...,
        *,
        tol: float = ...,
        max_iter: int = ...,
    ) -> None: ...
    def fit(self, x: Matrix, y: Vector) -> RegressionFit: ...

class SEstimator:
    def __init__(
        self,
        loss: LossArg = ...,
        *,
        delta: float | None = ...,
        n_subsamples: int = ...,
        seed: int | None = ...,
        tol: float = ...,
        max_iter: int = ...,
    ) -> None: ...
    def fit(self, x: Matrix, y: Vector) -> RegressionFit: ...

class MMEstimator:
    def __init__(
        self,
        s_loss: LossArg = ...,
        m_loss: LossArg = ...,
        *,
        n_subsamples: int = ...,
        seed: int | None = ...,
        tol: float = ...,
        max_iter: int = ...,
    ) -> None: ...
    def fit(self, x: Matrix, y: Vector) -> RegressionFit: ...

class Lts:
    def __init__(
        self,
        *,
        coverage: float | None = ...,
        n_subsamples: int = ...,
        seed: int | None = ...,
        tol: float = ...,
        max_iter: int = ...,
    ) -> None: ...
    def fit(self, x: Matrix, y: Vector) -> LtsFit: ...

def theil_sen(x: ArrayLike1D, y: ArrayLike1D) -> TheilSenFit: ...

# --- Multivariate --------------------------------------------------------------

class ScatterFit:
    @property
    def location(self) -> Vector: ...
    @property
    def scatter(self) -> Matrix: ...
    @property
    def distances(self) -> Vector: ...
    @property
    def weights(self) -> Vector: ...
    def distance_cutoff(self, quantile: float) -> float: ...
    def outliers(self, quantile: float) -> list[bool]: ...

class McdFit:
    @property
    def location(self) -> Vector: ...
    @property
    def scatter(self) -> Matrix: ...
    @property
    def distances(self) -> Vector: ...
    @property
    def weights(self) -> Vector: ...
    @property
    def raw_location(self) -> Vector: ...
    @property
    def raw_scatter(self) -> Matrix: ...
    @property
    def support(self) -> list[int]: ...
    @property
    def coverage(self) -> int: ...
    @property
    def objective(self) -> float: ...
    @property
    def breakdown_point(self) -> float: ...
    def distance_cutoff(self, quantile: float) -> float: ...
    def outliers(self, quantile: float) -> list[bool]: ...

class TylerFit:
    @property
    def location(self) -> Vector: ...
    @property
    def shape(self) -> Matrix: ...
    @property
    def distances(self) -> Vector: ...
    def outliers_assuming_chi2_radial(self, quantile: float) -> list[bool]: ...

class Mcd:
    def __init__(
        self,
        *,
        coverage: float | None = ...,
        n_subsamples: int = ...,
        reweight: bool = ...,
        seed: int | None = ...,
        tol: float = ...,
        max_iter: int = ...,
    ) -> None: ...
    def fit(self, x: Matrix) -> McdFit: ...

class Ogk:
    def __init__(
        self,
        scale: ScaleArg = ...,
        *,
        n_iter: int = ...,
        reweight: bool = ...,
    ) -> None: ...
    def fit(self, x: Matrix) -> ScatterFit: ...

class MScatter:
    def __init__(
        self,
        loss: LossArg = ...,
        *,
        tol: float = ...,
        max_iter: int = ...,
    ) -> None: ...
    def fit(self, x: Matrix) -> ScatterFit: ...

class Tyler:
    def __init__(
        self,
        *,
        location: ArrayLike1D | None = ...,
        tol: float = ...,
        max_iter: int = ...,
    ) -> None: ...
    def fit(self, x: Matrix) -> TylerFit: ...

def mahalanobis_distances(x: Matrix, loc: ArrayLike1D, scatter: Matrix) -> Vector: ...
def classical_covariance(x: Matrix) -> tuple[Vector, Matrix]: ...
def distance_cutoff(p: int, quantile: float) -> float: ...
def outlier_flags(distances: ArrayLike1D, p: int, quantile: float) -> list[bool]: ...

datasets: ModuleType
